### ISSUE TITLE
 Hello, I want to try this tool specifically. Can you help me？

### ISSUE THREAD

**Issue by 971106029** [FIRMCORN-Fuzzing/FIRMCORN#1]
Hello, I am a beginner. I read the pdf of this project introduction. This project is very cool. But helpless, my English level is average. I see that this project is also being maintained by many excellent Chinese researchers. Is there a specific Chinese version of the documentation or a detailed description of how to use this tool?

您好，我是一个初学者。我看了这个项目介绍的pdf。这个项目写的非常酷。但是无奈我的英文水平一般。我看到这个项目也有很多优秀的中国研究者在维护，请问是否有具体的中文版介绍文档或者此工具的详细使用方式介绍？

**Comment by FIRMCORN-Fuzzing** [comment]
Hi,
It may be helpful to provide a manual in Chinese, but unfortunately we are currently focusing on how to make the framework more versatile, and there are no plans to provide a manual in Chinese.

**Comment by 971106029** [comment]
Thank you very much for responding to me during your busy schedule. I hope your team can make correct and general research results. Of course, if a detailed manual is produced after the final development, it will make it easier for people to get started with this open source software and fall in love with it. thank you very much!
